### ISSUE TITLE
Publishing to the vsixgallery fails

### ISSUE THREAD

**Issue by ricksladkey** [jaredpar/VsVim#2497]
When appveyor builds VsVim, it is configured to publish it to vsixgallery. From `appveyor.yaml`:

```yaml
after_test:
  # Pushes the compiled vsix to artifacts and publishes it to vsixgallery.com
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
```

But the following output is a recent example of the appveyor build output for commits to master:

```
Vsix-PushArtifacts | Vsix-PublishToGallery
Uploading artifact VsVim.vsix (36,246,334 bytes)...100%
OK
Publish to VSIX Gallery...Vsix-PublishToGallery : FAIL
At line:1 char:22
+ Vsix-PushArtifacts | Vsix-PublishToGallery
+                      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Vsix-PublishToGallery
 
Vsix-PublishToGallery : Exception of type 'Microsoft.PowerShell.Commands.WriteErrorException' was thrown.
At line:1 char:22
+ Vsix-PushArtifacts | Vsix-PublishToGallery
+                      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Vsix-PublishToGallery
 ```

As a result, no nightly builds of VsVim have been published since late February.
